from . import help
from . import start
from . import admin
from . import menyu
from . import kategoriya
from . import back
from . import baliq
from . import miqdor
from . import drink
from . import secondly
from . import shashlik
from . import zakuski
from . import salat
from . import shurva
from . import non
from . import kombo
from . import sets
from . import savatcha
from . import delete
from . import buyurtma