from . import amount
from . import asosiy
from . import baliqlar
from . import categoriya
from . import drinks
from . import ikkinchi
from . import shashlik_turi
from . import zakuska
from . import salats
from . import shurvalar
from . import bread
from . import kombolar
from . import shash_set